Repository sulu/sulu-docs, pull requests merged in 2020-04, with the labels that each got.

#501 Add cache headers for webp
  cookbook/web-server/apache.rst
  cookbook/web-server/nginx.rst
Labels: Performance

#503 Remove web server bundle commands from docs
  book/getting-started.rst
  cookbook/web-server/built-in.rst
Labels: DX

#502 Azure Blob config
  cookbook/external-media-storage.rst
Labels: Missing Documentation

#505 Add documentation about the preview cache
  bundles/preview/index.rst
  bundles/preview/preview-cache.rst
  bundles/preview/preview-object-provider.rst
  cookbook/external-media-storage.rst
Labels: Missing Documentation

#512 Fix cacheLifetime closing tag
  book/templates.rst
Labels: Bug

#511 Add description to use deep links within a smart content field
  cookbook/smart-content-data-provider.rst
Labels: Missing Documentation

#516 Fix error parameters and default locale provider table
  cookbook/change-default-locale-provider.rst
  cookbook/custom-error-page.rst
Labels: Bug

#517 Remove currentContent from error twig parameters
  cookbook/custom-error-page.rst
Labels: Missing Documentation

#514 Update documentation about document fixtures
  reference/components/document-manager/fixtures.rst
Labels: Missing Documentation
