Repository sulu/sulu-docs, pull requests merged in 2020-11, with the labels that each got.

#578 Add extending block settings docs
  reference/content-types/block.rst
Labels: Missing Documentation

#577 Add docs about provide sulu twig attributes
  cookbook/index.rst
  cookbook/sulu-twig-attributes.rst
Labels: Missing Documentation

#554 Change example from recipe to event
  bundles/route/custom_route_generator.rst
  bundles/route/index.rst
Labels: DX

#586 Fix code highlighting for block settings example
  reference/content-types/block.rst
Labels: Bug
