Repository sulu/sulu-docs, pull requests merged in 2020-09, with the labels that each got.

#546 Add credentials to jackrabbit authentication
  cookbook/jackrabbit.rst
Labels: DX

#547 Use title instead of name as alt in example
  book/twig.rst
Labels: DX

#548 Add section aboute visibleCondition and disabledCondition
  book/templates.rst
Labels: Missing Documentation

#551 Fix docs about host configuration for sitemap dump
  cookbook/dump-sitemap.rst
Labels: Bug

#553 Add hint for updating database schema in audience targeting bundle docs
  bundles/audience_targeting.rst
Labels: DX

#552 Add preview form example
  bundles/preview/index.rst
  bundles/preview/preview-form-builder.rst
Labels: Missing Documentation

#558 Add link to Sulu Javascript Docs in Extend Admin section
  book/extend-admin.rst
Labels: DX

#560 Add documentation about https
  cookbook/https.rst
  cookbook/index.rst
Labels: Missing Documentation

#533 Add datetime content type documentation
  reference/content-types/date.rst
  reference/content-types/datetime.rst
  reference/content-types/index.rst
Labels: Missing Documentation
