Repository sulu/sulu-docs, pull requests merged in 2020-05, with the labels that each got.

#520 Add warning that values expression of select is only evaluated on initial request
  reference/content-types/select.rst
  reference/content-types/single_select.rst
Labels: DX

#524 Fix service definition for SmartContent DataProvider
  cookbook/smart-content-data-provider.rst
Labels: Bug

#525 Add categories and tag to extend entities documentaiton
  cookbook/extend-entities.rst
Labels: DX, Missing Documentation
