Repository sulu/sulu-docs, pull requests merged in 2022-07, with the labels that each got.

#723 Add immutable cache header to nginx
  cookbook/web-server/nginx.rst
Labels: Performance

#724 Add docs for markup data provider attribute configuration
  bundles/markup/link.rst
Labels: Missing Documentation

#727 Fix type in package name scheb/2fa-trusted-device not scheb/2fa-trusted-devices
  bundles/security/index.rst
Labels: Bug
